version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
  elasticsearch:
    hostname: "elasticsearch"
    container_name: "elasticsearch-docker"
    image: "laisgs/imdb_academy:indexed_elastic"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
