version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    environment:
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"